version: "3.8"

services:

  ###────────────────────────────────────────────────────────────────────────────
  # 1) kiosk1: chromium in kiosk mode on DISPLAY=:0.0 (first HDMI)
  kiosk1:
    build:
      context: ./kiosk
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    volumes:
      - ./data/kiosk1-profile:/home/kiosk/.config/chromium
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0.0
      - LIBGL_ALWAYS_SOFTWARE=1
    command: >
      chromium
        --noerrdialogs
        --disable-translate
        --disable-infobars
        --kiosk 
          "https://soundscreen.soundcheckvn.com/connect?screen=1"

  ###────────────────────────────────────────────────────────────────────────────
  # 2) kiosk2: chromium in kiosk mode on DISPLAY=:0.1 (second HDMI)
  kiosk2:
    build:
      context: ./kiosk
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    volumes:
      - ./data/kiosk2-profile:/home/kiosk/.config/chromium
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0.1
      - LIBGL_ALWAYS_SOFTWARE=1
    command: >
      chromium
        --noerrdialogs
        --disable-translate
        --disable-infobars
        --kiosk 
          "https://soundscreen.soundcheckvn.com/connect?screen=2"

  ###────────────────────────────────────────────────────────────────────────────
  # 3) controller: Node‐based proxy listening on port 8080
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    container_name: suitestream-device
    # host networking so:
    #  • HTTP on port 8080 is directly the Pi’s port 8080
    #  • socket.io connects without extra NAT
    network_mode: host
    privileged: true
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/cec0:/dev/cec0
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - "/:/host:rw"
    environment:
      # Point to your central server
      - CENTRAL_URL=https://soundscreen.soundcheckvn.com
      - CONNECT_URL=https://soundscreen.soundcheckvn.com/connect
      - POLL_INTERVAL_MS=2000
      - PORT=8080
    restart: unless-stopped
